[phases.setup]
nixPkgs = ['nodejs_22']

[phases.install]
cmds = ['npm install --prefix api --legacy-peer-deps --include=dev']

[phases.build]
cmds = ['cd api && npm run build']

[start]
cmd = 'node api/dist/main.js'
