[phases.setup]
nixPkgs = ['nodejs_22']

[phases.install]
cmds = ['cd api && npm install --legacy-peer-deps']

[phases.build]
cmds = ['cd api && ./node_modules/.bin/nest build && ls -la dist/']

[start]
cmd = 'node api/dist/main.js'
